      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TigerBot-IPA
          # Мы расширили путь, чтобы он нашел файл в любой подпапке bin
          path: |
            bin/*.ipa
            .buildozer/ios/platform/*/*.ipa
