name: iOS Build
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install System dependencies
        run: |
          # Устанавливаем только то, чего нет, не вызывая ошибку
          brew install autoconf automake libtool pkg-config wget || brew upgrade autoconf automake libtool pkg-config wget || true
          pip3 install --upgrade pip
          pip3 install Cython==0.29.33 buildozer kivy-ios

      - name: Build IPA
        run: |
          # Автоматическое подтверждение всех запросов Buildozer
          yes | buildozer ios debug
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TigerBot-IPA
          path: bin/*.ipa
