name: iOS Build
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install System dependencies
        run: |
          # Установка системных инструментов
          brew install autoconf automake libtool pkg-config wget || true
          
          # Установка Python инструментов с обходом защиты системы
          python3 -m pip install --upgrade pip --break-system-packages
          python3 -m pip install Cython==0.29.33 buildozer kivy-ios --break-system-packages

      - name: Build IPA
        run: |
          # Запуск основной сборки
          yes | buildozer ios debug
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TigerBot-IPA
          path: bin/*.ipa
