name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      # Установка Python и зависимостей
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython
          brew install automake autoconf libtool pkg-config

      # Запуск сборки
      - name: Build with Buildozer
        run: |
          # Исправление прав доступа (иногда нужно для GitHub Actions)
          chmod +x main.py 
          yes | buildozer ios debug

      # Сохранение готового файла
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TigerApp-iOS
          path: bin/*.ipa
