name: iOS Build
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Install System dependencies
        run: |
          brew install autoconf automake libtool pkg-config wget
          pip3 install --user --upgrade buildozer Cython==0.29.33 kivy-ios

      - name: Build IPA
        run: |
          # Команда сборки для iOS
          buildozer ios debug
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: TigerBot-IPA
          path: bin/*.ipa
