name: iOS Build
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install autoconf automake libtool pkg-config wget
          pip3 install --user --upgrade Cython==0.29.33 buildozer kivy-ios

      - name: Build IPA
        run: |
          # Принудительно создаем структуру проекта iOS
          yes | buildozer ios debug
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TigerBot-IPA
          path: bin/*.ipa
