name: iOS Build
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          brew install autoconf automake libtool pkg-config wget || true
          python3 -m pip install --upgrade pip
          python3 -m pip install Cython==0.29.33 buildozer kivy-ios packaging jinja2

      - name: Build IPA
        run: |
          python3 -m buildozer ios clean
          # Собираем дебаг-версию
          yes | python3 -m buildozer ios debug
          # Выводим список всех созданных файлов в лог для проверки
          echo "--- Список найденных файлов ---"
          find . -name "*.ipa"
          find . -name "*.app"
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TigerBot-Bundle
          # Мы забираем всё: и папку bin, и папку с готовым приложением .app
          path: |
            bin/*.ipa
            .buildozer/ios/platform/*/*.app
          if-no-files-found: warn
